import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercises = [
  { name: '1/2 Kneeling Shotgun Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
  { name: 'Air Bike', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Assisted Dip', category: 'COMPOUND' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'MACHINE' as const },
  { name: 'Back Extensions', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Back Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Bench Press', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Glute Bridge', category: 'COMPOUND' as const, primaryMuscle: 'GLUTES' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Hip Thrust', category: 'COMPOUND' as const, primaryMuscle: 'GLUTES' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Incline Bench Press', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Shoulder Press', category: 'COMPOUND' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'BARBELL' as const },
  { name: 'Barbell Step Up', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'BARBELL' as const },
  { name: 'Behind the Back Cable Bicep Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Bench Dip', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Bent Over Barbell Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BARBELL' as const },
  { name: 'Bicycle Crunch', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Bulgarian Split Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Cable Bicep Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Crossover Fly', category: 'ISOLATION' as const, primaryMuscle: 'CHEST' as const, equipment: 'CABLE' as const },
  { name: 'Cable Crunch', category: 'ISOLATION' as const, primaryMuscle: 'CORE' as const, equipment: 'CABLE' as const },
  { name: 'Cable Face Pull', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Lateral Raise', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'CABLE' as const },
  { name: 'Cable One Arm Tricep Side Extension', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable One Arm Underhand Tricep Extension', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Rear Delt Fly', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Rope Hammer Curls', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Rope Overhead Triceps Extension', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Rope Tricep Extension', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
  { name: 'Cable Tricep Pushdown', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cable Underhand Tricep Pushdown', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'CABLE' as const },
  { name: 'Cat Cow', category: 'STRETCHING' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Chest Doorway Stretch', category: 'STRETCHING' as const, primaryMuscle: 'CHEST' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Chin Up', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Close-Grip Bench Press', category: 'COMPOUND' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Cross Body Hammer Curls', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Crunches', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Dead Hang', category: 'OTHER' as const, primaryMuscle: 'BACK' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Deadlift', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BARBELL' as const },
  { name: 'Decline Push Up', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Decline Sit Up', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Dip', category: 'COMPOUND' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Dumbbell Bench Press', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Bent Over Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Bicep Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Bulgarian Split Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Fly', category: 'ISOLATION' as const, primaryMuscle: 'CHEST' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Front Raise', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Goblet Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Incline Bench Press', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Lateral Raise', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Lunge', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Rear Delt Raise', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Romanian Deadlift', category: 'COMPOUND' as const, primaryMuscle: 'HAMSTRINGS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Shoulder Press', category: 'COMPOUND' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Shrug', category: 'ISOLATION' as const, primaryMuscle: 'BACK' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Squat To Shoulder Press', category: 'COMPOUND' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'DUMBBELL' as const },
  { name: 'Dumbbell Sumo Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'DUMBBELL' as const },
  { name: 'EZ-Bar Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'EZ-Bar Overhead Tricep Extension', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Hack Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Hammer Curls', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Hammerstrength Chest Press', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'MACHINE' as const },
  { name: 'Hammerstrength Iso Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'MACHINE' as const },
  { name: 'Hanging Leg Raise', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Hiking', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Incline Dumbbell Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Incline Dumbbell Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'DUMBBELL' as const },
  { name: 'Incline EZ-Bar Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Incline Hammer Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Inverted Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Landmine Squat to Press', category: 'COMPOUND' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'BARBELL' as const },
  { name: 'Lat Pulldown', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
  { name: 'Leg Extension', category: 'ISOLATION' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Leg Press', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Leg Pull-In', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Leg Raise', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Leg Swing', category: 'STRETCHING' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Loop Band Shoulder Internal Rotation', category: 'STRETCHING' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'BANDS' as const },
  { name: 'Loop Band Standing Tricep Extension', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BANDS' as const },
  { name: 'Low Cable Chest Fly', category: 'ISOLATION' as const, primaryMuscle: 'CHEST' as const, equipment: 'CABLE' as const },
  { name: 'Lunge Twist', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Machine Fly', category: 'ISOLATION' as const, primaryMuscle: 'CHEST' as const, equipment: 'MACHINE' as const },
  { name: 'Machine Rear Delt Fly', category: 'ISOLATION' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'MACHINE' as const },
  { name: 'Machine Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Overhead PVC Shoulder Stretch', category: 'STRETCHING' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'OTHER' as const },
  { name: 'PVC Around the World', category: 'STRETCHING' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'OTHER' as const },
  { name: 'PVC Forearm Stretch', category: 'STRETCHING' as const, primaryMuscle: 'FOREARMS' as const, equipment: 'OTHER' as const },
  { name: 'Pike Push Up', category: 'COMPOUND' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Plank', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Preacher Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Prone W\'s', category: 'STRETCHING' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Pull Up', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Push Press', category: 'COMPOUND' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'BARBELL' as const },
  { name: 'Push Up', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Renegade Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'DUMBBELL' as const },
  { name: 'Reverse Barbell Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Reverse Grip Pull Down', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
  { name: 'Romanian Deadlift', category: 'COMPOUND' as const, primaryMuscle: 'HAMSTRINGS' as const, equipment: 'BARBELL' as const },
  { name: 'Rowing', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Running', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Running - Treadmill', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Seated Dumbbell Curl', category: 'ISOLATION' as const, primaryMuscle: 'BICEPS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Seated Leg Curl', category: 'ISOLATION' as const, primaryMuscle: 'HAMSTRINGS' as const, equipment: 'MACHINE' as const },
  { name: 'Single Arm Lat Pulldown', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
  { name: 'Single Leg Leg Extension', category: 'ISOLATION' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Skullcrusher', category: 'ISOLATION' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BARBELL' as const },
  { name: 'Sled Pull', category: 'COMPOUND' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Sled Push', category: 'COMPOUND' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Smith Machine Bench Press', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'MACHINE' as const },
  { name: 'Smith Machine Calf Raise', category: 'ISOLATION' as const, primaryMuscle: 'CALVES' as const, equipment: 'MACHINE' as const },
  { name: 'Smith Machine Glute Bridge', category: 'COMPOUND' as const, primaryMuscle: 'GLUTES' as const, equipment: 'MACHINE' as const },
  { name: 'Smith Machine Single-Leg Split Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Smith Machine Squat', category: 'COMPOUND' as const, primaryMuscle: 'QUADS' as const, equipment: 'MACHINE' as const },
  { name: 'Stair Stepper', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Standing Dumbbell Shoulder Press', category: 'COMPOUND' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'DUMBBELL' as const },
  { name: 'Standing Machine Calf Press', category: 'ISOLATION' as const, primaryMuscle: 'CALVES' as const, equipment: 'MACHINE' as const },
  { name: 'Straight-Arm Pulldown', category: 'ISOLATION' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
  { name: 'T-Bar Row', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'BARBELL' as const },
  { name: 'Tricep Stretch', category: 'STRETCHING' as const, primaryMuscle: 'TRICEPS' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Vertical Knee Raise', category: 'OTHER' as const, primaryMuscle: 'CORE' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Walking', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Walking - Treadmill', category: 'CARDIO' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Walkout to Push Up', category: 'COMPOUND' as const, primaryMuscle: 'CHEST' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Wall Ball', category: 'COMPOUND' as const, primaryMuscle: 'FULL_BODY' as const, equipment: 'OTHER' as const },
  { name: 'Wall Pectoral Stretch', category: 'STRETCHING' as const, primaryMuscle: 'CHEST' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Wall Slide Stretch', category: 'STRETCHING' as const, primaryMuscle: 'SHOULDERS' as const, equipment: 'BODYWEIGHT' as const },
  { name: 'Wide Grip Lat Pulldown', category: 'COMPOUND' as const, primaryMuscle: 'BACK' as const, equipment: 'CABLE' as const },
];

async function main() {
  console.log('Seeding exercise library...');
  let count = 0;
  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { id: `00000000-0000-0000-0000-${String(count + 1).padStart(12, '0')}` },
      update: {},
      create: {
        id: `00000000-0000-0000-0000-${String(count + 1).padStart(12, '0')}`,
        name: ex.name,
        category: ex.category,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: [],
        equipment: ex.equipment,
        source: 'MANUAL',
        isCustom: false,
      },
    });
    count++;
  }
  console.log(`Seeded ${count} exercises.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
